### ISSUE TITLE
Activate href with Enter key, 2nd

### ISSUE THREAD

**Issue by Green-1** [gibbok/jquery-slidertv#3]
Dear gibbok,

Thank you very much for answering the previous issue, but I am sorry bothering you again.
Inserting an `<a>` tag with href is not the problem. The link that you were referring to looks gorgeous. Thanks a lot!
But, instead of a mouse click to start a movie, I would like to use the enter key on the keyboard. The controls of the slider would then simply be: left/right arrow keys for navigation and enter key to launch href.
Is this possible?

Regards, Alex

**Comment by gibbok** [comment]
Hi Alex. Yes it is possible.
First of all you need to detect when an User press enter key on the keyboard, for this you can use jQuery with the following code:

```
$(document).keypress(function(e) {
    if(e.which == 13) {
    }
});
```

At this point you need to detect which item in the carousel is focused (a focused item will have a CSS class named `sliderTV--focus` applied). 

Use a selector like the following to select it (please keep in mind you need to modify the selector in order to match your actual DOM).

`$( ".sliderTV--focus" )`.

At the point you can lunch your media or whatever you like using any attribute you have added of your DOM element.

Happy coding.

**Comment by Green-1** [comment]
Hi gibbok,
Thanks for your hints. As I said in my first post, I am still learning js (still at the beginning), as it is just a hobby, not my profession. I see how far I will come with your tips.
Regards, Alex

**Comment by gibbok** [comment]
Hi Alex, if you need further help, you can also post a question on [Stack Overflow](http://stackoverflow.com/), many developers are there ready to help, included me :)

Regards
