### ISSUE TITLE
Click Events

### ISSUE THREAD

**Issue by BurtBurts** [gibbok/jquery-slidertv#4]
Hi there @gibbok 
Just wondering how to detect and trigger an event on click - as in if the user has an item selected, and clicks enter on the remote, it triggers the link that's placed on the image.

Can't figure out how to hijack the enter key on the remote and map it to an active item's link.

**Comment by gibbok** [comment]
Hi @BurtBurts,  you can try the following.

First of all you need to detect when an User press enter key on the keyboard, for this you can use jQuery with the following code. The number `13` is the code for a computer keyboard, but a Smart TV could have a different code depending on your model, please change it accordingly.

````
$(document).keypress(function(e) {
    if(e.which == 13) {
    }
});
````
At this point you need to detect which item in the carousel is focused (a focused item will have a CSS class named sliderTV--focus applied).

Use a selector like the following to select it (please keep in mind you need to modify the selector in order to match your actual DOM).
````
$( ".sliderTV--focus" ).
````
At the point you can lunch your media or whatever you like using any attribute you have added of your DOM element, in your case you can  trigger a click using jQuery as in the following code:
````
$( ".sliderTV--focus" ).trigger( "click" );
````
Happy coding.
